# Generated by Django 2.0.3 on 2018-03-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass_word',
            new_name='password',
        ),
    ]
